classDiagram
  class PresentationLayer {
  <<Interface>>
  +UserController
  +PlaceController
  +AmenityController
  +ReviewController
}

  class BusinessLogicLayer {
  +UserModel
  +PlaceModel
  +AmenityModel
  +ReviewModle
}

  class PersistenceLayer {
  +DatabaseAccess
  +Database
}

PresentationLayer --> BusinessLagicLayer : Facade Pattern
BusinessLogicLayer --> PersistenceLayer : Database Operations
